import type { Metadata } from 'next'
import { TronGlobe } from '@/components/3d/TronGlobe'
import { GlassCard } from '@/components/ui/GlassCard'
import { SectionHeadline } from '@/components/ui/SectionHeadline'
import { GlassButton } from '@/components/ui/GlassButton'
export const metadata: Metadata = { title: 'About', description: 'Coinductor makes everyday crypto sending simpler.' }
const values = [
  { title: 'Keep it simple', description: 'Sending crypto should feel as clear as sending money to someone you know.' },
  { title: 'Keep it personal', description: 'Coinductor is built for your own wallet and the people you want to pay.' },
  { title: 'Keep keys with you', description: 'Your keys stay on your phone, so your wallet remains yours.' },
]
export default function AboutPage() { return <div className="pt-24 pb-16"><section className="relative min-h-[70vh] flex items-center overflow-hidden px-4"><div className="absolute inset-0 opacity-20 pointer-events-none"><TronGlobe /></div><div className="relative z-10 max-w-6xl mx-auto w-full"><SectionHeadline title="Crypto sending, made" accent=" more human." subtitle="Coinductor helps you send USDT simply, without asking you to understand the fee mechanics behind every transfer." /><div className="mt-8 flex gap-4"><GlassButton variant="solid" href="/features">See the Product</GlassButton><GlassButton variant="outline" href="/contact">Get in Touch</GlassButton></div></div></section><section className="py-16 px-4"><div className="max-w-3xl mx-auto"><GlassCard className="p-10"><h2 className="font-grifter font-bold text-3xl mb-6" style={{ color: 'var(--on-surface)' }}>Why we built Coinductor</h2><div className="space-y-4 font-poppins leading-relaxed text-sm" style={{ color: 'var(--on-surface-2)' }}><p>Crypto can make a straightforward send feel harder than it needs to be. We built Coinductor to keep the details clear and the experience personal.</p><p>Smart Send handles the fee side of a transfer, while OTO Pass and DApp Pass offer simple ways to get started or take more control.</p></div></GlassCard></div></section><section className="py-16 px-4"><div className="max-w-6xl mx-auto"><SectionHeadline title="What we believe in" align="center" className="mb-12" /><div className="grid grid-cols-1 md:grid-cols-3 gap-6">{values.map((v, i) => <GlassCard key={v.title} className="p-8" scrollLinked><div className="w-8 h-8 rounded-lg flex items-center justify-center mb-4" style={{ background: 'rgba(11,131,255,0.12)' }}><span className="font-grifter font-bold text-sm" style={{ color: 'var(--primary)' }}>{i + 1}</span></div><h3 className="font-grifter font-bold text-xl mb-3" style={{ color: 'var(--on-surface)' }}>{v.title}</h3><p className="font-poppins text-sm leading-relaxed" style={{ color: 'var(--on-surface-2)' }}>{v.description}</p></GlassCard>)}</div></div></section></div> }
